# Generated by Django 4.2.5 on 2025-01-01 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbgibankmodel',
            options={'ordering': ['-created'], 'verbose_name': 'BBGI Finance Information', 'verbose_name_plural': 'BBGI Finance Informations'},
        ),
        migrations.AlterModelOptions(
            name='paymentinformation',
            options={'ordering': ['-created'], 'verbose_name': 'Payment Information', 'verbose_name_plural': 'Payment Informations'},
        ),
    ]
