# Generated by Django 4.2.5 on 2024-10-27 14:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_enddate',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 10, 27, 14, 42, 11, 509516, tzinfo=datetime.timezone.utc), 'Event end date and time cannot be in the past')]),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_startdate',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 10, 27, 14, 42, 11, 509464, tzinfo=datetime.timezone.utc), 'Event start date and time cannot be in the past')]),
        ),
        migrations.AlterField(
            model_name='eventtickettypemodel',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 10, 27, 14, 42, 11, 513327, tzinfo=datetime.timezone.utc), 'Ticket sale end date and time cannot be in the past')]),
        ),
        migrations.AlterField(
            model_name='eventtickettypemodel',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 10, 27, 14, 42, 11, 513274, tzinfo=datetime.timezone.utc), 'Ticket sale start date and time cannot be in the past')]),
        ),
    ]
