# Generated by Django 4.2.5 on 2024-11-13 23:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventmodel_event_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='email',
            field=models.EmailField(default='+27663409363', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='phone',
            field=models.CharField(default='a@a.com', help_text='Enter cellphone number', max_length=15, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-9][0-9]{8}$', 'RSA phone number is required')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_enddate',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 11, 13, 23, 6, 38, 263932, tzinfo=datetime.timezone.utc), 'Event end date and time cannot be in the past')]),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_startdate',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 11, 13, 23, 6, 38, 263880, tzinfo=datetime.timezone.utc), 'Event start date and time cannot be in the past')]),
        ),
        migrations.AlterField(
            model_name='eventtickettypemodel',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 11, 13, 23, 6, 38, 267878, tzinfo=datetime.timezone.utc), 'Ticket sale end date and time cannot be in the past')]),
        ),
        migrations.AlterField(
            model_name='eventtickettypemodel',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 11, 13, 23, 6, 38, 267805, tzinfo=datetime.timezone.utc), 'Ticket sale start date and time cannot be in the past')]),
        ),
    ]
