# Generated by Django 4.2.5 on 2024-12-26 12:51

import datetime
import django.core.validators
from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventcontent_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcontent',
            name='some_field',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventcontent',
            name='image',
            field=models.ImageField(default='i', help_text='Upload emages images.', upload_to=events.models.handle_event_file_upload),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_enddate',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 12, 26, 12, 50, 56, 472241, tzinfo=datetime.timezone.utc), 'Event end date and time cannot be in the past')]),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_startdate',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 12, 26, 12, 50, 56, 472183, tzinfo=datetime.timezone.utc), 'Event start date and time cannot be in the past')]),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='comment_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='commenter_full_names',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='rating_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='eventtickettypemodel',
            name='sale_end',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 12, 26, 12, 50, 56, 480313, tzinfo=datetime.timezone.utc), 'Ticket sale end date and time cannot be in the past')]),
        ),
        migrations.AlterField(
            model_name='eventtickettypemodel',
            name='sale_start',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 12, 26, 12, 50, 56, 480259, tzinfo=datetime.timezone.utc), 'Ticket sale start date and time cannot be in the past')]),
        ),
    ]
