# Generated by Django 4.2.5 on 2024-10-27 14:42

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markets.utilities.file_handlers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=markets.utilities.file_handlers.handle_service_file_upload)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField()),
                ('price_decription', models.CharField(blank=True, default='', help_text='Enter service price decription e.g Callout fee', max_length=150, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Enter service price e.g 300.00', max_digits=1000, null=True)),
                ('on_discount', models.BooleanField(default=False)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Enter discount percentage, e.g 100', max_digits=1000, null=True)),
                ('discount_description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='listings.business')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Qoutation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='business/qoutation/')),
                ('full_names', models.CharField(max_length=350)),
                ('phone', models.CharField(help_text='Enter your cellphone number', max_length=15, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-9][0-9]{8}$', 'RSA phone number is required')])),
                ('email', models.EmailField(help_text='Enter your email address', max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_location_based', models.BooleanField(default=False, help_text='Does this job need to be done on a specific location?')),
                ('location', models.CharField(blank=True, help_text='Enter your location, e.g 123 St, KZN, 3915', max_length=350, null=True)),
                ('call_at', models.CharField(choices=[('Morning(7am - 12pm)', 'Morning(7am - 12pm)'), ('Afternoon (12pm - 5pm)', 'Afternoon (12pm - 5pm)'), ('Late (5pm - till late)', 'Late (5pm - till late)'), ('Anytime', 'Anytime')], help_text='When should we contact you?', max_length=150)),
                ('time', models.CharField(choices=[("I'm flexible", "I'm flexible"), ('As soon as possible', 'As soon as possible'), ('It an emergency', 'It an emergency'), ('Approved Payout', 'Approved Payout'), ('I have a specific date in mind', 'I have a specific date in mind')], help_text='When do you need the service to be completed?', max_length=150)),
                ('date', models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 10, 27, 14, 42, 11, 526501, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoutations', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoutations', to='markets.service')),
            ],
            options={
                'verbose_name': 'Qoutation Request',
                'verbose_name_plural': 'Qoutation Requests',
                'ordering': ['-created'],
            },
        ),
    ]
