# Generated by Django 4.2.5 on 2024-10-27 14:36

import accounts.utilities.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import listings.utilities.file_handlers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('background_image', models.ImageField(blank=True, help_text='Upload company/business background image.', null=True, upload_to=listings.utilities.file_handlers.handle_business_file_upload)),
                ('logo', models.ImageField(blank=True, help_text='Upload company/business logo.', null=True, upload_to=listings.utilities.file_handlers.handle_business_file_upload)),
                ('title', models.CharField(help_text='Enter title for your company/business', max_length=150, unique=True)),
                ('slogan', models.CharField(blank=True, max_length=350, null=True, verbose_name='Enter your business slug')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('details', models.TextField(blank=True, help_text='Enter additional details about your company/business', null=True)),
                ('main_address', models.CharField(blank=True, help_text='Enter main office address seperated by comma', max_length=300, null=True)),
                ('map_coordinates', models.CharField(blank=True, max_length=300, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='Enter your business email')),
                ('bbbee_level', models.CharField(choices=[('BEL1', 'BEE Level 1'), ('BEL2', 'BEE Level 2'), ('BEL3', 'BEE Level 3'), ('BEL4', 'BEE Level 4'), ('BEL5', 'BEE Level 5'), ('BEL6', 'BEE Level 6'), ('BEL7', 'BEE Level 7'), ('NOT', 'Not sure'), ('NC', 'Non-compliance')], max_length=100)),
                ('province', models.CharField(choices=[('kzn', 'KwaZulu-Natal'), ('mp', 'Mpumalanga'), ('nw', 'North-West'), ('fs', 'Free-State'), ('wc', 'Western Cape'), ('lp', 'Limpopo'), ('gp', 'Gauteng'), ('ec', 'Eastern Cape'), ('nc', 'Northern Cape')], max_length=300)),
                ('phone', models.CharField(blank=True, help_text='Enter your business number', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-9][0-9]{8}$', 'RSA phone number is required')])),
                ('alternative_phone', models.CharField(blank=True, help_text='Enter your business number', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-9][0-9]{8}$', 'RSA phone number is required')])),
                ('facebook', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_fcbk_link])),
                ('twitter', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_twitter_link])),
                ('instagram', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_insta_link])),
                ('linkedIn', models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_in_link])),
                ('status', models.CharField(choices=[('NOT APPROVED', 'Not approved'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('Completed', 'Completed'), ('Blocked', 'Blocked')], default='NOT APPROVED', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='category/business/')),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('label', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BusinessReview',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rating_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commenter_email', models.EmailField(max_length=254)),
                ('commenter_full_names', models.CharField(max_length=250)),
                ('comment_title', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.business')),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Review',
                'verbose_name_plural': 'Business Reviews',
            },
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location_title', models.CharField(blank=True, help_text='Enter your business branch name', max_length=350, null=True)),
                ('email', models.EmailField(blank=True, help_text='Enter your business branch email', max_length=250, null=True)),
                ('phone', models.CharField(blank=True, help_text='Enter your business branch number', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-9][0-9]{8}$', 'RSA phone number is required')])),
                ('address', models.CharField(help_text='Enter office address seperated by comma', max_length=400)),
                ('map_coordinates', models.CharField(blank=True, max_length=300, null=True)),
                ('address_id', models.CharField(blank=True, max_length=300, null=True)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_locations', to='listings.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessContent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, help_text='Upload company/business images.', null=True, upload_to=listings.utilities.file_handlers.handle_business_file_upload)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='listings.category'),
        ),
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default=('TU', 'Tuesday'), max_length=250)),
                ('operating', models.BooleanField(default=True)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='listings.business')),
            ],
            options={
                'verbose_name': 'Business Hour',
                'verbose_name_plural': 'Business Hours',
                'unique_together': {('business', 'day')},
            },
        ),
    ]
