# Generated by Django 4.2.5 on 2025-01-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
    ]
