# Generated by Django 4.2.5 on 2024-12-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
