# Generated by Django 4.2.5 on 2024-12-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aboutcompany_mission_aboutcompany_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='mission',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='vision',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
