# Generated by Django 4.2.5 on 2024-11-24 14:39

import campaigns.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaignmodel_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='event_address',
            field=models.CharField(blank=True, help_text='Enter event address seperated by comma', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='map_coordinates',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter cellphone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-9][0-9]{8}$', 'RSA phone number is required')]),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='end_date',
            field=models.DateTimeField(default=campaigns.models.in_fourteen_days, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 11, 24, 14, 39, 51, 394010, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")]),
        ),
    ]
