# Generated by Django 4.2.5 on 2024-11-24 14:44

import campaigns.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignmodel_email_campaignmodel_event_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignmodel',
            name='event_address',
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='campaign_address',
            field=models.CharField(blank=True, help_text='Enter campaign address seperated by comma', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='end_date',
            field=models.DateTimeField(default=campaigns.models.in_fourteen_days, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 11, 24, 14, 44, 45, 785120, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")]),
        ),
    ]
