# Generated by Django 4.2.5 on 2024-11-24 17:01

import accounts.utilities.validators
import campaigns.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_campaignmodel_event_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmodel',
            name='alternative_phone',
            field=models.CharField(blank=True, help_text='Enter your business number', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\+27|0)[1-9][0-9]{8}$', 'RSA phone number is required')]),
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='facebook',
            field=models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_fcbk_link]),
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='instagram',
            field=models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_insta_link]),
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='linkedIn',
            field=models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_in_link]),
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='twitter',
            field=models.URLField(blank=True, null=True, validators=[accounts.utilities.validators.validate_twitter_link]),
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='end_date',
            field=models.DateTimeField(default=campaigns.models.in_fourteen_days, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 11, 24, 17, 1, 12, 999110, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")]),
        ),
    ]
