# Generated by Django 4.2.5 on 2024-11-24 17:17

import campaigns.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaignmodel_alternative_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmodel',
            name='small_description',
            field=models.TextField(blank=True, help_text='Small description about your campaign for search optimization.', null=True),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='end_date',
            field=models.DateTimeField(default=campaigns.models.in_fourteen_days, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 11, 24, 17, 17, 52, 156334, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")]),
        ),
    ]
