# Generated by Django 4.2.5 on 2024-11-24 21:29

import campaigns.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0006_campaignmodel_small_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmodel',
            name='end_date',
            field=models.DateTimeField(default=campaigns.models.in_fourteen_days, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 11, 24, 21, 29, 18, 862923, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")]),
        ),
        migrations.CreateModel(
            name='CampaignReview',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rating_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commenter_email', models.EmailField(max_length=254)),
                ('commenter_full_names', models.CharField(max_length=250)),
                ('comment_title', models.CharField(max_length=250)),
                ('comment', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='campaigns.campaignmodel')),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Review',
                'verbose_name_plural': 'Campaign Reviews',
            },
        ),
        migrations.CreateModel(
            name='CampaignContent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, help_text='Upload emages images.', null=True, upload_to='campaigns/images/')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='campaigns.campaignmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
