# Generated by Django 4.2.5 on 2024-12-26 12:51

import campaigns.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaignmodel_end_date_campaignreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncontent',
            name='image',
            field=models.ImageField(default='h', help_text='Upload emages images.', upload_to='campaigns/images/content/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='end_date',
            field=models.DateTimeField(default=campaigns.models.in_fourteen_days, validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 12, 26, 12, 50, 56, 453536, tzinfo=datetime.timezone.utc), "Date should not be less that today's date")]),
        ),
        migrations.AlterField(
            model_name='campaignreview',
            name='commenter_full_names',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='campaignreview',
            name='rating_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
